### ISSUE TITLE
Documetation for Install

### ISSUE THREAD

**Issue by devopstales** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#1]
It would be nice if you can create a Documentation how to install it.

**Comment by ryecoaaron** [comment]
How to install the plugin or how to use the plugin?

**Comment by devopstales** [comment]
Install.

**Comment by ryecoaaron** [comment]
install omv 5.x.
install omv-extras.  https://forum.openmediavault.org/index.php/Thread/5549-OMV-Extras-org-Plugin/
enable Testing repo in omv-extras Settings tab.
Install plugin from Plugins tab.
Use plugin

**Comment by devopstales** [comment]
O.. That is for OVM5. I tried to find it with OVM4. That was my problem.
