### ISSUE TITLE
Image size displays zero for large images (1 TB)

### ISSUE THREAD

**Issue by frederictobiasc** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#10]
Hi,
when creating large images (example: 1 TB), the image size is displayed as 0. This seems to be caused by an overflow of php's filesize function in [tgt.inc](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt/blob/240d8b8d6a412ab0f77493a47f0e21ceaa994ccb/usr/share/openmediavault/engined/rpc/tgt.inc#L165)
![file_size](https://user-images.githubusercontent.com/26125115/147609659-5f3a9751-853b-4b68-a4f4-9a3053dac0c6.png)

**Comment by ryecoaaron** [comment]
It could also be a limit in the web framework.  I will check.

**Comment by ryecoaaron** [comment]
I can't reproduce this.
![image](https://user-images.githubusercontent.com/1914475/147611823-776553fe-e9a8-4dd4-9334-f13631dde83f.png)

**Comment by frederictobiasc** [comment]
I executed the filesize()-function directly and it shows the same behaviour.
```
nas:~:# php -a                      
Interactive mode enabled

php > $a = filesize('/etc/openmediavault/config.xml');
php > printf("%u", $a);
21239
php > $a = filesize('/srv/dev-disk-by-uuid-23e54a5b-e08b-49a9-af88-cffc88d9e84e/backup-nb-regina/test');
php > printf("%u", $a);
0
^C

nas:~:# ls -lh /srv/dev-disk-by-uuid-23e54a5b-e08b-49a9-af88-cffc88d9e84e/backup-nb-regina/test
-rw-rw-rw- 1 root root 500G Dec 28 21:55 /srv/dev-disk-by-uuid-23e54a5b-e08b-49a9-af88-cffc88d9e84e/backup-nb-regina/test
```

**Comment by ryecoaaron** [comment]
What kind of system are you using? The php page does have this note:

Because PHP's integer type is signed and many platforms use 32bit integers, some filesystem functions may return unexpected results for files which are larger than 2GB.

**Comment by frederictobiasc** [comment]
It's an Odroid HC2 based on the armv7l architecture, which is 32 bit.

**Comment by ryecoaaron** [comment]
Luckily, I have an test HC2 running OMV 6.x that I can test on.  Hopefully I can find something that works.

**Comment by ryecoaaron** [comment]
Fixed and working on my odroid hc2.  I will push a new package later.

**Comment by frederictobiasc** [comment]
Cool, thanks for the quick fix.

**Comment by ryecoaaron** [comment]
6.0.3 is in the repo now.
