### ISSUE TITLE
Grow of image don't work?

### ISSUE THREAD

**Issue by ovz93br43v7** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#13]
Hello,

probably I'm doing something wrong but I have created for testing purposes a 1GB image, mounted it successfully.
I now used the grow function of the plugin to 10GB, this is now showed in the webGUI.

But I don't get the bigger size on my initiator / client PC? (reboot done, checked with gparted and fdisk -l --> still 1GB)

Any hint what to do?

Thanks in advance!

**Comment by ryecoaaron** [comment]
You need to rescan the LUN and grow the filesystem.

**Comment by ovz93br43v7** [comment]
You are right, sorry for this dumb question.
