### ISSUE TITLE
No problem but idea

### ISSUE THREAD

**Issue by colem76** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#3]
Hello,

I did not find or ask you this.
Is it planned to be able to create and manage virtual disks.

I think this would be necessary, but I don't know if you had thought about it.

**Comment by ryecoaaron** [comment]
I hadn't thought about it but it is a good idea.  I have been using LVs since that can be done easily in the web interface.  I could add another tab that would allow images to be created.  I would give the option to make the image sparse or not.  Not sure if I want to add the ability to increase the size of an existing image.

**Comment by ryecoaaron** [comment]
5.1.0 in the repo now has an image management tab.  Pretty basic but should get the job done.

**Comment by colem76** [comment]
i have uninstall and reinstall
i havre this error

```
Erreur #0:
OMV\Config\DatabaseException: Failed to execute XPath query '/config/services/tgt'. in /usr/share/php/openmediavault/config/database.inc:78
Stack trace:
#0 /usr/share/openmediavault/engined/module/tgt.inc(31): OMV\Config\Database->get('conf.service.tg...')
#1 /usr/share/openmediavault/engined/rpc/services.inc(58): OMVModuleTgt->getStatus()
#2 [internal function]: Engined\Rpc\Services->getStatus(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getStatus', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Services', 'getStatus', Array, Array, 1)
#6 {main}

```

EDIT: ok i have found the problem

**Comment by ryecoaaron** [comment]
Did you clear the browser cache to fix the problem?
