### ISSUE TITLE
Backing Store

### ISSUE THREAD

**Issue by ahmaddxb** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#4]
What should i be entering for the backing store

![image](https://user-images.githubusercontent.com/43728586/99881031-a26c7000-2c30-11eb-93a8-602bc9415e2d.png)

**Comment by ryecoaaron** [comment]
See the man page for targets.conf under backing store - https://linux.die.net/man/5/targets.conf.  Typically, it would be an LVM LV or an image file that you can create on the Images tab.

**Comment by ahmaddxb** [comment]
Can this be used to connect to an ISCSI NAS and share its content with OMV?

**Comment by ryecoaaron** [comment]
The tgt plugin is an iscsi server not client.  You don't need a plugin for iscsi client.  If you present an iSCSI LUN to an OMV system, it should just show up in the Physical Disks tab.  Then you should be able to create a filesystem on that LUN in the Filesystems tab.

**Comment by ahmaddxb** [comment]
ok thanks, will try to figure that out.

**Comment by ryecoaaron** [comment]
I have never used a Drobo.  So, I can't help there.
