### ISSUE TITLE
IQN's are generated incorrectly

### ISSUE THREAD

**Issue by pietervandersluis** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#5]
I ran in an issue with another program that imports ISCSI luns. But before it does, it check if the naming is correct. It does this based on:  RFC 3720 and RFC 3721.

The IQN's generated here are `iqn.yyyy.m.com.example`. According to the rfc it should be: `iqn.yyyy.mm.com.example`

I suspect that this line generates the iqn name: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt/blob/master/usr/share/openmediavault/engined/rpc/tgt.inc#L121 

Kind regards,

Pieter

**Comment by pietervandersluis** [comment]
Did a small test with:

```php
<?php

    echo sprintf("%'02d\n", 7);   # represents the seventh month
    echo sprintf("%'02d\n", 11);  # represents the eleventh month

?>
```

It resulted in:

07
11

**Comment by ryecoaaron** [comment]
I should have used %s instead of %d since the date('m') is returning a two digit string.  I will fix.

**Comment by ryecoaaron** [comment]
Fixed in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-tgt/commit/4e2cc5297b61ac1f8dbafaa3eaf0c329af28d8e4

**Comment by ryecoaaron** [comment]
5.1.4 in the repo now.

**Comment by pietervandersluis** [comment]
Thanks, I hope you had a good weekend 👍
