### ISSUE TITLE
Create target with --tid 2

### ISSUE THREAD

**Issue by greenvespa** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#6]
Is it possible to use Extra Options on target creation with --tid 2 parameter?

I have 2 different OMV installations with tgt plugin and I need to have 2 different SCSI ID and SCSI SN on LUN 0 and LUN 1 because VMware needs different values to work correctly.

I tried to use Extra Options but I don't know which parameters work correctly.

I need something like this:
tgtadm --lld iscsi --op new --mode target --tid 2 -T iqn.2021-07.nas09:iscsi02
tgtadm --lld iscsi --op new --mode logicalunit --tid 2 --lun 1 -b /dev/vg.iscsi02/lv.iscsi02

Thanks.

**Comment by ryecoaaron** [comment]
In tgt share, I think you can add lun 0 or lun 1 in the extra options.  You should only need tid when using tgtadm so it knows which target to modify.

**Comment by ryecoaaron** [comment]
Or maybe not.  Looking at the example, you can set controller tid with the following in extra options:
controller_tid 10

https://github.com/fujita/tgt/blob/master/conf/examples/targets.conf.example#L185

**Comment by greenvespa** [comment]
> Or maybe not. Looking at the example, you can set controller tid with the following in extra options:
> controller_tid 10
> 
> https://github.com/fujita/tgt/blob/master/conf/examples/targets.conf.example#L185

It works! Thanks a lot!
