### ISSUE TITLE
little instruction to install and configure

### ISSUE THREAD

**Issue by onixd** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#7]
Could you please write a little instruction, how to install and configure this plugin? I`m install thirst time OMV 5.x. and I need iscsi target plugin. I hope I not only one :(

**Comment by ryecoaaron** [comment]
Which part do you need help with?

1. Enable the plugin
2. Create an image in the Images tab unless you are going to dedicate an entire disk or partition or logical volume
3. Create a target in the Targets tab
4. Use whatever you want for a name
5. Use the path of the image you just created or the path of the disk (ie /dev/sdX)
6. The address of the client or a range.

That's it.  If you are using Windows as a client, I can't help you with that.

**Comment by ovz93br43v7** [comment]
Hey thanks for the plugin and this small "guide" in how to use the plugin.

As a newbie I searched a while to find help how to mount this iSCSI drive in ubuntu.
I came quite far I think but I couldn't managed to get this completely working as normal user with automount on boot at my PC, so in case anybody can provide further input I would be very happy.

My steps so far:

On the OMV-nas do the following steps:
1. Create an image in the images tab (not existing sub-folders are not created automatically by the plugin) e.g. /mnt/iscsitest
2. In the target tab you have to put the path to the image at "backing store" e.g. /mnt/iscsitest and you have to click on "enable"
3. Don't forget to enable the plugin in the settings tab

On your client:
1. Open the terminal
2. You have to install this: `sudo apt install open-iscsi`
3. Find yout iSCSI target: `sudo iscsiadm -m discovery -t sendtargets -p IP-of-OMV:3260`
4. You will get an output like this `IP-of-OMV:3260,1 iqn.2022-01.hostname-of-OMV:iscsitest`
5. You now have to login in the iSCSI target: `sudo iscsiadm -m node -T iqn.2022-01.hostname-of-OMV:iscsitest -p IP-of-OMV:3260 --login`
6. With `sudo fdisk -l` you should now find a new device e.g.`/dev/sdx`. You can detect the iSCSI drive by looking for model "VIRTUAL-DISK"
7. Now we have to create a partition table on the iSCSI drive (gparted can be used also), terminal way: `sudo fdisk /dev/sdx`
8. In the fdisk menu: select "n" for new partition, after selecting the partition type, first and last sector you have to write the changes with "w"
9. Next step is to create a file-system on the iSCSI drive with `sudo mkfs.ext4 /dev/sdxy` e.g. `sudo mkfs.ext4 /dev/sdb1`
10. You need now a folder where you want to mount your iSCSI drive, e.g. /mnt or you create a new folder with `mkdir /path/to/iscsi` (use sudo when you create the folder outside of your home directory)
11. Now mount the iSCSI drive into the new created folder: `sudo mount  -t ext4 /dev/sdxy  /path/to/iscsi`
12. With `df -h` you should now find your iSCSI drive

I collected this all from various guides, forums, reddit partly from other unix / linux distro guides. But now I'm a bit lost:
- for automount the iSCSI drive on boot I think would be correct: `/etc/fstab`, e.g. `sudo nano /etc/fstab` and add `/dev/sdxy  /path/to/iscsi   ext4 _netdev,rw,users,auto 0 0`
- but when I add this to fstab shutdown and boot process of the PC take around 2 minutes longer as usual
- the iSCSI drive isn't mounted on boot up as actually planned
- additionally I could not manage to gain as normal user access to the iscsi drive

Thanks in advance

**Comment by ovz93br43v7** [comment]
Hi @ryecoaaron 

is the section "targets" --> "extra options" where I can add CHAP authentication? Or is it "settings" --> "extra options"?

e.g.
`incominguser iscsi-initiator password1`
`outgoinguser iscsi-target password2`

Thanks in advance!

**Comment by ryecoaaron** [comment]
I would guess in the target's extra options.  Never used CHAP.  You could post on the forum where more people would see your question though.

**Comment by ovz93br43v7** [comment]
> I would guess in the target's extra options. Never used CHAP. You could post on the forum where more people would see your question though.

I simply tried it, yes target's extra options!
