### ISSUE TITLE
Plugin can't create image

### ISSUE THREAD

**Issue by GodenX** [OpenMediaVault-Plugin-Developers/openmediavault-tgt#8]
I installed openmediavault 6.0.5-3(Shaitan) in RPi4B. The tgt version is 6.0.0. When create images, I used path "/srv/dev-disk-by-uuid-c12bed6c-7f04-4aba-96cb-497491831fb3/DiskImg" which is my disk mount path. But the image not be created, and the error message is "400 - Bad Request uuid: The value null is not a string". How can i do for this? Please help me, thanks!

**Comment by ryecoaaron** [comment]
I will push the fix shortly.

**Comment by ryecoaaron** [comment]
I pushed 6.0.2 to the repo.  I'm not sure if this fix your issue since I didn't find the issue I thought it would be.  If it doesn't, please post a screenshot of the settings that are not working.

**Comment by GodenX** [comment]
Thanks! The 6.0.2 has fix this bug.
